SELECT 
    ID AS PAYMENT_ID,
    ORDERID AS ORDER_ID,
    PAYMENTMETHOD AS PYMNT_MTHD,
    STATUS AS STATUS,
    AMOUNT/100 AS AMOUNT,
    CREATED AS CREATED,
    _BATCHED_AT AS BATCHED
FROM {{ source ('stripe', 'payment') }}
